### ISSUE TITLE
Popup placement for polylines

### ISSUE THREAD

**Issue by kyletolle** [Leaflet/Leaflet.toolbar#10]
When using the popup example, if you draw a polyline and then click on it, the edit popup appears below the point on the polyline on which you clicked.

![screenshot 2015-01-16 13 22 01](https://cloud.githubusercontent.com/assets/260869/5783767/38998510-9d83-11e4-984c-49b5fa15b93a.png)

Would it be possible to have the edit popup placed so that it appears to be right on or above the line instead of below it?

Somewhat related to #9.

**Comment by manleyjster** [comment]
Yes - this is exactly the same issue as #8. I originally designed the popup to appear immediately above the point clicked - but I noticed when I was last doing bugfixes that this isn't the case any more.

**Comment by manleyjster** [comment]
Should be fixed. Take a look at the latest examples: http://leaflet.github.io/Leaflet.toolbar/examples/popup.html#.

**Comment by kyletolle** [comment]
Yes, this is now fixed and works as expected. Thanks!
