### ISSUE TITLE
Rename JS files for better consistency with other Leaflet projects

### ISSUE THREAD

**Issue by kyletolle** [Leaflet/Leaflet.toolbar#11]
I went through the other Leaflet repos today, because I noticed some inconsistency with how some named their compiled JS files.

You can see a summary here:

![screenshot 2015-01-16 11 04 11](https://cloud.githubusercontent.com/assets/260869/5783895/7ad16b54-9d84-11e4-943f-faeb3c213d4c.png)

To be consistent with the majority of leaflet plugins, could we:
- Change `dist/Leaflet.Toolbar.js` to `dist/leaflet.toolbar-src.js`
- Change `dist/Leaflet.Toolbar.min.js` to `dist/leaflet.toolbar.js`

I didn't look at CSS files, although, in hindsight, I should have.

**Comment by manleyjster** [comment]
Yes, agree that consistency with other Leaflet plugins is desirable. This will be in the next batch of updates and tweaks.

**Comment by manleyjster** [comment]
Fixed by 1f1cd2b.
