### ISSUE TITLE
Add a function to show relevant pictures

### ISSUE THREAD

**Issue by Janjko** [Leaflet/Leaflet.toolbar#15]
It would be great to have the ability to list pictures like Google Maps does. Developer would find the extents of the map, get a Jason with a list of pictures that are relevant to the place, and then list them in your toolbar.

Is your toolbar the right place for something like this?

**Comment by manleyjster** [comment]
This is really outside the scope of Leaflet.toolbar. Leaflet.toolbar provides classes (i.e. generic templates) for creating toolbar interfaces. It sounds like you are looking for a location-aware image search plugin for Leaflet.

If it does not already exist, you may be able to build what you are looking for using other plugins for Leaflet: http://leafletjs.com/plugins.html.

Good luck!
