### ISSUE TITLE
Removing a toolbar brings up an error

### ISSUE THREAD

**Issue by fnicollet** [Leaflet/Leaflet.toolbar#19]
Hello and thanks for this useful library,

I am not sure if I am using the library the right way but I don't understand if the toolbar is supposed to be a Leaflet Control?
I can add a toolbar using addControl:
```javascript
this.toolbar = new L.Toolbar.Control({
                actions: actions,
                position: 'topleft',
                className: 'leaflet-draw-toolbar'
            });

            this.map.addControl(this.toolbar);
```
But I can't remove it with removeControl because the removeFrom method is not implemented in L.Toolbar.Control.

L.Toolbar inherits from L.Class, so it could be anything but from the name and behaviour, I believe it should behave like a Control? Because it can be a popup as well, you might have made it inherit from Class instead.

This is the method from Leaflet's L.Control:
```
removeFrom: function (map) {
		var pos = this.getPosition(),
		    corner = map._controlCorners[pos];

		corner.removeChild(this._container);
		this._map = null;

		if (this.onRemove) {
			this.onRemove(map);
		}

		return this;
	},
```

Thanks for your help,
Fabien

**Comment by fnicollet** [comment]
Note that adding 
```javascript
L.Toolbar.Control.prototype.removeFrom = function (map) {
            this.onRemove(map);
        }
```
Fixes the behaviour, so this is probably something forgotten during a refactoring

**Comment by manleyjster** [comment]
Hey @fnicollet - sorry for the confusion!

L.Toolbar.Control is *not* meant to implement `L.Control`. Similarly, L.Toolbar.Popup is *not* meant to implement `L.Popup`'s interface. Leaflet.toolbar provides a class for building toolbar UI's (L.Toolbar), as well as a built-in "control-style" toolbar (L.Toolbar.Control) and a built-in "popup-style" toolbar (L.Toolbar.Popup).

All toolbars deriving from `L.Toolbar` present an interface similar to the interface for feature layers. That is, toolbars can be added to maps using:
```javascript
toolbar.addTo(map); // preferred
```
or, alternatively:
```javascript
map.addLayer(toolbar);
```

Similarly, toolbars can be removed from maps by calling
```javascript
map.removeLayer(toolbar);
```

This is the result of a deliberate design decision that was intended to ensure a uniform API across all Leaflet.toolbar UI elements and make use of the familiar `#addLayer` and #removeLayer` methods provided by Leaflet core.

Sorry for the confusion! I've added a new note explaining this to the wiki: https://github.com/Leaflet/Leaflet.toolbar/wiki/API-Reference#adding-and-removing-toolbars.

**Comment by fnicollet** [comment]
ok, thanks for the precisions :)
