### ISSUE TITLE
Duplicated Leaflet.toolbar popups in online examples 

### ISSUE THREAD

**Issue by fnicollet** [Leaflet/Leaflet.toolbar#20]
Hello,
Examples found in the repo's readme are useful (although in the middle of a transition with Leaflet.draw so need to be patched) but the behaviour shown is sometimes buggy.

In the popup example:
http://leaflet.github.io/Leaflet.toolbar/examples/popup.html
Draw a rectangle, click on it once and and then again at some other place in the rectangle and the popup is duplicated.

Fabien

**Comment by manleyjster** [comment]
Ah yes - this is a duplicate of #3. This issue has been fixed, but the examples were stale. I just updated them, and it should be working now! Thanks for the reminder!

**Comment by fnicollet** [comment]
Works well, thanks!
