### ISSUE TITLE
Does this plugin prevent use of latest Leaflet.Draw?

### ISSUE THREAD

**Issue by jhoover75** [Leaflet/Leaflet.toolbar#31]
This plugin defines L.Toolbar, which Leaflet Draw also defines.  Does use of this plugin prevent me from using the latest Leaflet.Draw?

**Comment by justinmanley** [comment]
Hmmm. Unfortunately, yes. This plugin was originally intended to replace the toolbar defined in Leaflet.draw with a more flexible toolbar, but it hasn't been fully integrated into Leaflet.draw yet.

If you want to use Leaflet.toolbar and Leaflet.draw, your best bet right now is to use the [`integrating-toolbar` branch of Leaflet.draw](https://github.com/Leaflet/Leaflet.draw/commits/integrating-toolbar).
