### ISSUE TITLE
About released files

### ISSUE THREAD

**Issue by pvnr0082t** [Leaflet/Leaflet.toolbar#37]
Hi @justinmanley,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team and want to host this library.
There are some problems:
1. The js file has a minified release, but the css file doesn't, so that we need to manually minify it, the most common naming policy is ```name.ext``` -> ```name.min.ext```, so we'll minify ```leaflet.toolbar.css``` to ```leaflet.toolbar.min.css```, so the js file and css file will have different naming policy, 
2. We want to apply auto-update on all the libs, so that once you release a new version, we'll get it very soon, but the auto-update process can not recognize the mixed naming schem, so that it can not automatically minify and publish the new versions, which means we can not use auto-update on it.

I'll respectfully suggest you consider to also provide the minified css file, no matter what's the naming schem, since there is already minified file, so that we don't need to manually minify the project, then the naming isn't that important, another way is to change the filename of ```leaflet.toolbar.js```, name the source file ```leaflet.toolbar.js``` and the minified file ```leaflet.toolbar.min.js```, so the naming will be consistent, the automatically minify process can easily handle it.

Thanks.

https://github.com/cdnjs/cdnjs/pull/7857
https://github.com/cdnjs/cdnjs/issues/7779

**Comment by justinmanley** [comment]
Added a minified CSS file ([leaflet.toolbar.css](https://github.com/Leaflet/Leaflet.toolbar/blob/master/dist/leaflet.toolbar.css)) and renamed the unminified version to [leaflet.toolbar-src.css](https://github.com/Leaflet/Leaflet.toolbar/blob/master/dist/leaflet.toolbar-src.css).
