### ISSUE TITLE
Move to Leaflet org?

### ISSUE THREAD

**Issue by mourner** [Leaflet/Leaflet.toolbar#4]
This looks like a wonderful, high-quality plugin. We have Leaflet.draw in the Leaflet organization — if it is ported to use Leaflet.Toolbar, I think it would make sense to move the latter to the Leaflet org as well, so it's Leaflet/Leaflet.Toolbar. What do you think?

**Comment by manleyjster** [comment]
thanks! yes, that sounds good.  What's the best way to go about it?

**Comment by mourner** [comment]
I've temporarily added you to Leaflet org owners. Once you accept the invitation, you can go to this repo settings and push the "Transfer ownership" button. Once you transfer the repo to the Leaflet org, I'll move you from "owners" to a team with full rights to the Leaflet.Toolbar repo. Meanwhile you'll update the links in the repo to point to new addresses.

**Comment by manleyjster** [comment]
Renamed it to follow the Leaflet org lowercase naming convention. I'll go through and update links and other references later today or tomorrow.

**Comment by mourner** [comment]
:+1:
