### ISSUE TITLE
Subtoolbar with leaflet1rc.1 problem

### ISSUE THREAD

**Issue by rendrom** [Leaflet/Leaflet.toolbar#40]
Problems with the subtoolbar with leaflet library version "1.0.0-rc.1".

![leaflet toolbar_subtoolbarproblem](https://cloud.githubusercontent.com/assets/1478481/15641564/663910c8-2674-11e6-9514-ec6d8b4ff304.JPG)

**Comment by rendrom** [comment]
```
appendToContainer: function(container) {
		var constructor = (this.parentToolbar && this.parentToolbar.constructor) || this.constructor;
		var baseClass = constructor.baseClass + '-' + this._calculateDepth(),
                //...
}
```
these changes (and some css) enough for my app

**Comment by justinmanley** [comment]
Thanks for noticing this, @rendrom! I'm happy to accept a PR, if you want to put together a PR with the code that worked for you.

**Comment by rendrom** [comment]
https://github.com/rendrom/Leaflet.toolbar
This code work for me, but still have some problem: the subtoolbar does not close by `toolbar-0` ico clicking.

**Comment by justinmanley** [comment]
Fixed with https://github.com/justinmanley/leaflet-draw-toolbar.
