### ISSUE TITLE
About naming schema

### ISSUE THREAD

**Issue by pvnr0082t** [Leaflet/Leaflet.toolbar#43]
Hi @justinmanley ,
We are [cdnjs](https://github.com/cdnjs/cdnjs) team, we want to host this project in cdnjs.
We'll like to make the filename consistent but v0.1.0 is using different naming schemam, and there is no minified css file. I'd like to discuss if it's possible to change to the most common naming style like this:
- javascript.js -> javascript.min.js
- style.css -> style.min.css

Thank you.

https://github.com/cdnjs/cdnjs/pull/7857
https://github.com/cdnjs/cdnjs/issues/7779

**Comment by justinmanley** [comment]
Fixed in version 0.2.1.
