### ISSUE TITLE
Make Leaflet.toolbar compatible with Leaflet.draw

### ISSUE THREAD

**Issue by justinmanley** [Leaflet/Leaflet.toolbar#47]
Leaflet.toolbar has been incompatible with Leaflet.draw since its earliest release, since both libraries define L.Toolbar differently.

I created https://github.com/Leaflet/Leaflet.draw/pull/354 to switch Leaflet.draw to use Leaflet.toolbar. The Leaflet.draw maintainer began merging the PR, but never completed it, so the two libraries remain incompatible. This is a significant problem, since Leaflet.draw is the primary intended client of Leaflet.toolbar.

Two possible approaches to making the two libraries compatible:
  1. Complete the PR in https://github.com/Leaflet/Leaflet.draw/pull/354
  2. Move Leaflet.toolbar from L.Toolbar -> L.Toolbar2 (or similar), and add a "compatibility mode" function in L.toolbar that replaces L.Toolbar in Leaflet.draw with a proxy class that conforms to the Leaflet.draw API, but forwards to L.Toolbar2. This would allow the two libraries to exist side-by-side.

**Comment by robi10101298** [comment]
I hope also that it will be compatible, because I need to use this for polygons... Do you know any alternative to it? All I need is to change the color of a polygon when I edit it with color picker. Thanks!

**Comment by justinmanley** [comment]
Fixed with https://github.com/justinmanley/leaflet-draw-toolbar.
