### ISSUE TITLE
L.Toolbar is undefined

### ISSUE THREAD

**Issue by karlitos** [Leaflet/Leaflet.toolbar#48]
I installed _Leaflet.toolbar_ with npm `npm install npm install leaflet-toolbar` and used the `import` statement to get it referenced in my javascript file `import leaflet-toolbar`.

Sadly, the `L.Toolbar` object is undefined. this s how my __L__ object looks like:

```javascript
{version: "1.2.0", Browser: {…}, noConflict: ƒ, Control: ƒ, control: ƒ, …}
Bounds: ƒ Bounds(a, b)
Browser: {ie: false, ielt9: false, edge: false, webkit: true, android: false, …}
CRS: {latLngToPoint: ƒ, pointToLatLng: ƒ, project: ƒ, unproject: ƒ, scale: ƒ, …}
Canvas: ƒ ()
Circle: ƒ ()
CircleMarker: ƒ ()
Class: ƒ Class()
Control: ƒ ()
DivIcon: ƒ ()
DivOverlay: ƒ ()
DomEvent: {on: ƒ, off: ƒ, stopPropagation: ƒ, disableScrollPropagation: ƒ, disableClickPropagation: ƒ, …}
DomUtil: {TRANSFORM: "transform", TRANSITION: "webkitTransition", TRANSITION_END: "webkitTransitionEnd", get: ƒ, getStyle: ƒ, …}
Draggable: ƒ ()
EditControl: ƒ ()
Editable: ƒ ()
Evented: ƒ ()
FeatureGroup: ƒ ()
GeoJSON: ƒ ()
GridLayer: ƒ ()
Handler: ƒ ()
Icon: ƒ ()
ImageOverlay: ƒ ()
LatLng: ƒ LatLng(lat, lng, alt)
LatLngBounds: ƒ LatLngBounds(corner1, corner2)
Layer: ƒ ()
LayerGroup: ƒ ()
LineUtil: {simplify: ƒ, pointToSegmentDistance: ƒ, closestPointOnSegment: ƒ, clipSegment: ƒ, _getEdgeIntersection: ƒ, …}
Map: ƒ ()
Marker: ƒ ()
Mixin: {Events: {…}}
NewGebietControl: ƒ ()
NewSpaControl: ƒ ()
Path: ƒ ()
Point: ƒ Point(x, y, round)
PolyUtil: {clipPolygon: ƒ}
Polygon: ƒ ()
Polyline: ƒ ()
Popup: ƒ ()
PosAnimation: ƒ ()
Projection: {LonLat: {…}, Mercator: {…}, SphericalMercator: {…}}
Rectangle: ƒ ()
Renderer: ƒ ()
SVG: ƒ ()
TileLayer: ƒ ()
Tooltip: ƒ ()
Transformation: ƒ Transformation(a, b, c, d)
Util: {lastId: 0, freeze: ƒ, extend: ƒ, create: ƒ, bind: ƒ, …}
VideoOverlay: ƒ ()
bind: ƒ bind(fn, obj)
bounds: ƒ toBounds(a, b)
canvas: ƒ canvas$1(options)
circle: ƒ circle(latlng, options, legacyOptions)
circleMarker: ƒ circleMarker(latlng, options)
control: ƒ (options)
divIcon: ƒ divIcon(options)
extend: ƒ extend(dest)
featureGroup: ƒ (layers)
geoJSON: ƒ geoJSON(geojson, options)
geoJson: ƒ geoJSON(geojson, options)
gridLayer: ƒ gridLayer(options)
icon: ƒ icon(options)
imageOverlay: ƒ (url, bounds, options)
latLng: ƒ toLatLng(a, b, c)
latLngBounds: ƒ toLatLngBounds(a, b)
layerGroup: ƒ (layers)
map: ƒ createMap(id, options)
marker: ƒ marker(latlng, options)
noConflict: ƒ noConflict()
point: ƒ toPoint(x, y, round)
polygon: ƒ polygon(latlngs, options)
polyline: ƒ polyline(latlngs, options)
popup: ƒ (options, source)
rectangle: ƒ rectangle(latLngBounds, options)
setOptions: ƒ setOptions(obj, options)
stamp: ƒ stamp(obj)
svg: ƒ svg$1(options)
tileLayer: ƒ tileLayer(url, options)
toolbar: {control: ƒ, popup: ƒ}
toolbarAction: ƒ (t)
tooltip: ƒ (options, source)
transformation: ƒ toTransformation(a, b, c, d)
version: "1.2.0"
videoOverlay: ƒ videoOverlay(video, bounds, options)
__proto__: Object
```

**Comment by justinmanley** [comment]
Thanks for reporting this, Karel. The library was recently updated and I neglected to update the documentation. I've updated the documentation now.

You should use `LeafletToolbar` rather than `L.Toolbar` as the namespace for classes in this library. I recommend that you take a look at the [API reference](https://github.com/leaflet/Leaflet.Toolbar/wiki/API-Reference). If you are using this library to add advanced Leaflet.draw functionality, I also recommend taking a look at [leaflet-draw-toolbar](https://github.com/justinmanley/leaflet-draw-toolbar).

**Comment by karlitos** [comment]
Thanks for the response, could you please give me a hint how to access the `LeafletToolbar` instance ? I would like to to use the ES6 import. As stated above my global `L` object does have neither 'LeafletToolbar' nor 'Toolbar', only 'toolbar'

**Comment by justinmanley** [comment]
Sorry, Karel - Leaflet.toolbar does not yet support ES6 modules (i.e. no "import { LeafletToolbar } from 'leaflet-toolbar'"). You should use the global "LeafletToolbar" object for the time being. I will work on exposing Leaflet.toolbar as an ES6 module. This will hopefully land in the next few weeks.

**Comment by karlitos** [comment]
Hi Justin, thanks for clarification, but my actual concern is how to access the global object without having to put the `<script>` and `<link>` tags in the HTML.

I tried:
* `import LeafletToolbar from 'leaflet-toolbar';`
* `import * as LeafletToolbar from 'leaflet-toolbar/dist/leaflet.toolbar.js';`
* `const LeafletToolbar = require('leaflet-toolbar/dist/leaflet.toolbar.js');` 

but `LeafletToolbar` is always empty Object

**Comment by justinmanley** [comment]
Karel - I've renamed the namespace from LeafletToolbar to L.Toolbar2. Please give it a try now (use leaflet-toolbar@0.4.0-alpha.1 and leaflet-draw-toolbar@0.3.0-alpha.1). Once I get the OK from you I'll promote the alphas to full releases.

**Comment by karlitos** [comment]
Hi Justin, I would love to test it, but my current working setup is VueJS2 with webpack/template, I tried to put the `leaflet.toolbar.js` and `leaflet.toolbar.css` into the _static_ folder, reference those files in my main _HTML_ file and start the server in the production-mode, but it gives me
```javascript
leaflet.toolbar.js:1 Uncaught ReferenceError: L is not defined
    at leaflet.toolbar.js:1
    at leaflet.toolbar.js:1
```
at start at weird VueJS error-messages later. I have to wait for any possibility to _require/import_ the library to test it properly. Thanks anyway for your effort.

**Comment by justinmanley** [comment]
How do you include the Leaflet JS in your site? Including the Leaflet.toolbar JS in the same way should allow you to access it via "require":
  1. Include leaflet-toolbar in your webpack config.
  2. require('leaflet') in your JS
  3. Access Leaflet.toolbar by referencing L.Toolbar2.*

**Comment by karlitos** [comment]
Hello Justin, I apologize for the delay, but at least I can confirm, that _leaflet-toolbar_ is working after the changs you introduced.

I had to require, the _leaflet.toolbar.js_, require or import the _leaflet.toolbar.css_ , than i basically copied the code from the examples and voila ... 😃 

Thanks for the effort 👍
