### ISSUE TITLE
popup toolbar width CSS issue

### ISSUE THREAD

**Issue by jywarren** [Leaflet/Leaflet.toolbar#52]
Hi! We saw this on MapKnitter and found a fix:

![image](https://user-images.githubusercontent.com/24359/53122360-4a5c8300-350b-11e9-8450-25ba71520339.png)

This CSS seems to fix it:

```css
.leaflet-toolbar-icon {
  box-sizing: initial;
}
```

See here:

![image](https://user-images.githubusercontent.com/24359/53122465-87287a00-350b-11e9-8960-5a3e3401812b.png)

https://github.com/publiclab/Leaflet.DistortableImage/commit/13a40ac6590ca80b6abc4a3aed960a0f17c445d4

I can open a PR in a moment.

**Comment by jywarren** [comment]
https://github.com/Leaflet/Leaflet.toolbar/pull/53 - thanks again!!! 🎉

**Comment by justinmanley** [comment]
Fixed in #53 - thanks, Jeff!
