### ISSUE TITLE
using with create-react-app

### ISSUE THREAD

**Issue by cubecleveland** [Leaflet/Leaflet.toolbar#58]
Hello, trying to use a simple implementation in react (using webpack)
not really trying to do any 'React' stuff but simple use the plugin with vaniall js.

I keep getting this errors: t.extend is not a function.

**Comment by IvanSanchez** [comment]
Hi, great to hear that you find Leaflet useful!

However, this issue tracker is used for reporting bugs and discussing new features. For questions on using Leaflet, please use [gis.stackexchange.com](https://gis.stackexchange.com/questions/tagged/leaflet) or [stackoverflow](https://stackoverflow.com/questions/tagged/leaflet).

If you are *really* sure that this is a bug in leaflet, or a feature request, please [change the wording to make it look like a bug report](http://www.chiark.greenend.org.uk/~sgtatham/bugs.html).
