### ISSUE TITLE
textual descriptions for tools where icons are ambiguous

### ISSUE THREAD

**Issue by jywarren** [Leaflet/Leaflet.toolbar#6]
I'm loathe to suggest actually adding text next to the icons; the compactness is great. But we just don't have enough (or good enough) icons to describe all the actions we're hoping to implement in [Leaflet.DistortableImage](https://github.com/publiclab/Leaflet.DistortableImage/), so some icons are understandably vague in purpose. 

I'm not sure how I feel about this design-wise, but what about tooltips? http://getbootstrap.com/javascript/#tooltips

**Comment by manleyjster** [comment]
Jeff - Leaflet.toolbar supports tooltips.

See: https://github.com/Leaflet/Leaflet.toolbar/wiki/API-Reference#toolbariconoptions.

An alternative, if you actually want the icon to consist of text, is to set the HTML property of the icon to a string describing what the icon should do (i.e. "Select") and then write some custom CSS to make sure that the icon is wide enough to hold the text.  This is actually how the sub-toolbar for the Leaflet.draw toolbar polyline drawing action ("Cancel" / "Delete last point") is implemented: http://leaflet.github.io/Leaflet.toolbar/examples/control.html.

**Comment by jywarren** [comment]
crossing in cyberspace. i see it now https://github.com/Leaflet/Leaflet.toolbar/search?utf8=%E2%9C%93&q=popup

**Comment by manleyjster** [comment]
For an example, see: https://github.com/manleyjster/Leaflet.draw/blob/leaflet-toolbar-plugin/src/draw/handler/Draw.Polygon.js#L20

**Comment by manleyjster** [comment]
haha yup!
