### ISSUE TITLE
click/drag events propagate to map

### ISSUE THREAD

**Issue by jywarren** [Leaflet/Leaflet.toolbar#7]
Is this an expected behavior? It means you can drag the map by dragging on the toolbar, and that clicking or double clicking on the toolbar affects the map. I can code around this, just curious.

**Comment by manleyjster** [comment]
Jeff - I pushed some commits that address this.

Clicking and double-clicking on the toolbar should no longer affect the map - see the latest example at http://leaflet.github.io/Leaflet.toolbar/examples/popup.html.

Dragging on the toolbar also no longer affects the map - but if you mousedown on the toolbar and then drag the cursor off the toolbar and onto the map, the map will also begin to drag.  Do you think this is a significant issue? It should be possible to disable this behavior as well, but it's more complicated (i.e. it'll involve disabling dragging on the map when there's a mousedown on the toolbar and, at the same time, adding a listener to enable dragging on the map as soon as there's a mouseup anywhere in the window).

**Comment by jywarren** [comment]
I think this is fine for now; it covers, importantly, all *intentional* use cases I can think of. Thanks!

**Comment by jywarren** [comment]
Oh, are you going to do a release soon? I'd like to add to DistortableImage and MapKnitter bower.json. Thanks!

**Comment by manleyjster** [comment]
I did a 0.1.0 release on npm a few weeks ago: https://www.npmjs.com/package/leaflet-toolbar. There's been a slew of issues since then, most of which have been addressed at this point. I plan on doing a 0.1.1 release over the weekend.

**Comment by jywarren** [comment]
super, thanks.
